package org.evochora.compiler.e2e;

import org.evochora.compiler.Compiler;
import org.evochora.compiler.api.ProgramArtifact;
import org.evochora.runtime.Simulation;
import org.evochora.runtime.internal.services.CallBindingRegistry;
import org.evochora.runtime.model.Environment;
import org.evochora.runtime.model.Molecule;
import org.evochora.runtime.model.Organism;
import org.evochora.runtime.isa.Instruction;
import org.evochora.runtime.isa.RegisterBank;
import org.evochora.runtime.model.EnvironmentProperties;
import org.evochora.test.utils.SimulationTestUtils;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Contains integration tests that verify the interaction between the compiler and the runtime simulation.
 * These tests compile source code, load the resulting artifact into a simulated environment,
 * execute the code, and then assert that the runtime behavior is correct.
 * These are tagged as "integration" tests because they span the compiler and runtime subsystems.
 */
public class RuntimeIntegrationTest {

	@BeforeAll
	static void setUp() {
		Instruction.init();
	}

	/**
	 * Compiles a procedure with parameters, loads it into a simulation, and runs it.
	 * This test verifies that the compiled code can be executed by an organism in the runtime environment.
	 * This is an integration test.
	 *
	 * @throws Exception if compilation or simulation fails.
	 */
	@Test
    @Tag("integration")
	void procedureWithParametersAddsValuesAtRuntime() throws Exception {
		String source = String.join("\n",
				"EXPORT .PROC ADD2 REF A B",
				"  ADDR A B",
				"  RET",
				".ENDP",
				"SETI %DR0 DATA:1",
				"SETI %DR1 DATA:2",
				"CALL ADD2 REF %DR0 %DR1",
				"NOP"
		);

		Compiler compiler = new Compiler();
		EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
		ProgramArtifact artifact = compiler.compile(Arrays.asList(source.split("\\r?\\n")), "rt_proc_params.s", envProps);
		assertThat(artifact).isNotNull();

		// Create a small environment and simulation
		Environment env = new Environment(envProps);
		Simulation sim = SimulationTestUtils.createSimulation(env);

		// Place program at origin (0,0)
		for (Map.Entry<int[], Integer> e : artifact.machineCodeLayout().entrySet()) {
			int[] rel = e.getKey();
			int[] abs = new int[]{rel[0], rel[1]};
			env.setMolecule(Molecule.fromInt(e.getValue()), abs);
		}

		Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
		org.setProgramId(artifact.programId());
		sim.addOrganism(org);

		// Run a few ticks to execute SETI, SETI, CALL, and within proc ADDR and RET
		for (int i = 0; i < 10; i++) sim.tick();

		// Basic runtime sanity checks
		assertThat(org.readOperand(0)).isNotNull();
		assertThat(org.readOperand(1)).isNotNull();
	}

    /**
     * Verifies that the compiled machine code for procedure calls is self-sufficient
     * and does not depend on the {@link ProgramArtifact} being available at runtime.
     * It compiles a program, loads the machine code, but withholds the artifact from the simulation.
     * The test passes if the procedure's side effect (modifying a register) is still correct,
     * proving that the PUSH/POP instructions generated by the compiler are solely responsible
     * for parameter passing.
	 * This is an integration test.
     *
     * @throws Exception if compilation or simulation fails.
     */
    @Test
    @Tag("integration")
    void procedureCopyOut_worksWithoutProgramArtifact() throws Exception {
        String source = String.join("\n",
                "SETI %DR0 DATA:41",
                "CALL INCREMENT REF %DR0",
                "WAIT",  // Use WAIT instead of NOP - NOP is instant-skip
                ".ORG 0|1",
                "EXPORT .PROC INCREMENT REF VALUE",
                "  ADDI VALUE DATA:1",
                "  RET",
                ".ENDP"

        );

        Compiler compiler = new Compiler();
        EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
        ProgramArtifact artifact = compiler.compile(Arrays.asList(source.split("\\r?\\n")), "artifact_free_test.s", envProps);
        assertThat(artifact).isNotNull();

        Environment env = new Environment(envProps);
        Simulation sim = SimulationTestUtils.createSimulation(env);
        sim.setProgramArtifacts(Collections.emptyMap());

        for (Map.Entry<int[], Integer> e : artifact.machineCodeLayout().entrySet()) {
            env.setMolecule(Molecule.fromInt(e.getValue()), e.getKey());
        }

        Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
        org.setProgramId(artifact.programId());
        sim.addOrganism(org);

        // Run exactly 9 ticks: SETI(1) + PUSH(2) + CALL(3) + POP(4) + ADDI(5) + PUSH(6) + RET(7) + POP(8) + WAIT(9)
        // Note: More ticks would cause instant-skip loop to wrap around grid and re-execute SETI!
        for (int i = 0; i < 9; i++) {
            sim.tick();
        }

        Molecule result = Molecule.fromInt((Integer) org.readOperand(0));
        assertThat(result.toScalarValue())
                .as("Der Wert sollte nach dem Prozeduraufruf auf 42 inkrementiert sein, auch ohne Artefakt.")
                .isEqualTo(42);
        assertThat(org.isInstructionFailed()).as("Failure: " + org.getFailureReason()).isFalse();
    }

    @Test
    @Tag("integration")
    void procedureCall_worksCorrectlyWithCorruptedProgramArtifact() throws Exception {
        String sourceCode = String.join("\n",
                "SETI %DR0 DATA:29",
                "CALL INC REF %DR0",
                "WAIT",  // Use WAIT instead of NOP - NOP is instant-skip
                ".ORG 0|1",
                "EXPORT .PROC INC REF A",
                "  ADDI A DATA:1",
                "  RET",
                ".ENDP"

        );

        Compiler compiler = new Compiler();
        EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
        ProgramArtifact correctArtifact = compiler.compile(Arrays.asList(sourceCode.split("\\r?\\n")), "correct.s", envProps);
        assertThat(correctArtifact).isNotNull();

        Map<Integer, Map<Integer, Integer>> corruptedBindings = new HashMap<>();
        correctArtifact.callSiteBindings().forEach((addr, bindings) -> {
            corruptedBindings.put(addr, Map.of(RegisterBank.FDR.base, 1));
        });

        ProgramArtifact corruptedArtifact = new ProgramArtifact(
                correctArtifact.programId(),
                correctArtifact.sources(),
                correctArtifact.machineCodeLayout(),
                correctArtifact.initialWorldObjects(),
                correctArtifact.sourceMap(),
                corruptedBindings,
                correctArtifact.relativeCoordToLinearAddress(),
                correctArtifact.linearAddressToCoord(),
                correctArtifact.registerAliasMap(),
                correctArtifact.procNameToParamNames(),
                correctArtifact.tokenMap(),
                correctArtifact.tokenLookup(),
                correctArtifact.sourceLineToInstructions(),
                correctArtifact.labelValueToName(),
                correctArtifact.labelNameToValue()
        );

        Environment env = new Environment(envProps);
        Simulation sim = SimulationTestUtils.createSimulation(env);

        for (Map.Entry<int[], Integer> e : correctArtifact.machineCodeLayout().entrySet()) {
            env.setMolecule(Molecule.fromInt(e.getValue()), e.getKey());
        }

        sim.setProgramArtifacts(Map.of(corruptedArtifact.programId(), corruptedArtifact));

        Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
        org.setProgramId(correctArtifact.programId());
        sim.addOrganism(org);

        CallBindingRegistry.getInstance().clearAll();
        for (var binding : corruptedArtifact.callSiteBindings().entrySet()) {
            int[] coord = corruptedArtifact.linearAddressToCoord().get(binding.getKey());
            if (coord != null) {
                CallBindingRegistry.getInstance().registerBindingForAbsoluteCoord(coord, binding.getValue());
            }
        }

        // Track instructions and register states
        //ExecutionTracker tracker = new ExecutionTracker(sim, org);

        // Run exactly 9 ticks: SETI(1) + PUSH(2) + CALL(3) + POP(4) + ADDI(5) + PUSH(6) + RET(7) + POP(8) + WAIT(9)
        // Note: More ticks would cause instant-skip loop to wrap around grid and re-execute SETI!
        for (int i = 0; i < 9; i++) {
        //    tracker.beforeTick();
            sim.tick();
        //    tracker.afterTick();
        }

        // Print execution trace
        //String trace = tracker.getTraceAsString();
        //System.out.println(trace);

        Molecule result = Molecule.fromInt((Integer) org.readOperand(0));
        assertThat(result.toScalarValue())
                .as("Das Ergebnis der Addition muss 30 sein, basierend auf dem Maschinencode, nicht dem falschen Artefakt.\n" /*+ trace*/)
                .isEqualTo(30);
        assertThat(org.isInstructionFailed()).isFalse();
    }

    /**
     * Verifies that PLR (Proc-Local Location Registers) are correctly saved on CALL
     * and restored on RET. PROC_A stores the active DP in %PLR0 via DPLR, then calls
     * PROC_B which overwrites %PLR0 with a different position. After PROC_B returns,
     * PROC_A's %PLR0 must be restored to the original value.
     */
    @Test
    @Tag("integration")
    void plrIsSavedAndRestoredAcrossProcedureCalls() throws Exception {
        String source = String.join("\n",
                // Main: call PROC_A
                "CALL PROC_A",
                "WAIT",
                // PROC_A at a different location
                ".ORG 0|1",
                "EXPORT .PROC PROC_A",
                "  DPLR %PLR0",          // Save current DP to PLR0
                "  CALL PROC_B",         // PROC_B will overwrite PLR0
                "  SKLR %PLR0",          // After return, PLR0 should be restored — move DP back
                "  RET",
                ".ENDP",
                // PROC_B at another location
                ".ORG 0|3",
                "EXPORT .PROC PROC_B",
                "  .REG %TMP %PLR0",     // Alias for readability
                "  CRLR %TMP",           // Clear PLR0 to [0,0] — overwrites caller's value
                "  RET",
                ".ENDP"
        );

        Compiler compiler = new Compiler();
        EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
        ProgramArtifact artifact = compiler.compile(Arrays.asList(source.split("\\r?\\n")), "plr_save_restore.s", envProps);
        assertThat(artifact).isNotNull();

        Environment env = new Environment(envProps);
        Simulation sim = SimulationTestUtils.createSimulation(env);

        for (Map.Entry<int[], Integer> e : artifact.machineCodeLayout().entrySet()) {
            env.setMolecule(Molecule.fromInt(e.getValue()), e.getKey());
        }

        Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
        org.setProgramId(artifact.programId());
        sim.addOrganism(org);

        // Run enough ticks to execute: CALL PROC_A, DPLR, CALL PROC_B, CRLR, RET, SKLR, RET, WAIT
        for (int i = 0; i < 20; i++) {
            sim.tick();
        }

        assertThat(org.isInstructionFailed()).as("Failure: " + org.getFailureReason()).isFalse();
    }

    /**
     * Verifies that SDR (Static Data Registers) persist across procedure calls
     * and are isolated between different procedures. COUNTER increments %SDR0
     * on each call, copies it to %DR0, then returns. Calling it three times
     * should yield DR0 == 3. A second procedure COUNTER_B copies its own %SDR0
     * to %DR1 — it should be 0 (independent backing store).
     */
    @Test
    @Tag("integration")
    void sdrPersistsAcrossCallsAndIsIsolatedBetweenProcedures() throws Exception {
        String source = String.join("\n",
                // Main: call COUNTER three times, then COUNTER_B once
                "CALL COUNTER",
                "CALL COUNTER",
                "CALL COUNTER",
                "CALL COUNTER_B",
                "WAIT",
                // COUNTER: increment SDR0, copy to DR0
                ".ORG 0|1",
                "EXPORT .PROC COUNTER",
                "  ADDI %SDR0 DATA:1",
                "  SETR %DR0 %SDR0",
                "  RET",
                ".ENDP",
                // COUNTER_B: copy SDR0 to DR1 (should be 0 — separate backing store)
                ".ORG 0|3",
                "EXPORT .PROC COUNTER_B",
                "  SETR %DR1 %SDR0",
                "  RET",
                ".ENDP"
        );

        Compiler compiler = new Compiler();
        EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
        ProgramArtifact artifact = compiler.compile(Arrays.asList(source.split("\\r?\\n")), "sdr_persistent.s", envProps);
        assertThat(artifact).isNotNull();

        Environment env = new Environment(envProps);
        Simulation sim = SimulationTestUtils.createSimulation(env);

        for (Map.Entry<int[], Integer> e : artifact.machineCodeLayout().entrySet()) {
            env.setMolecule(Molecule.fromInt(e.getValue()), e.getKey());
        }

        Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
        org.setProgramId(artifact.programId());
        sim.addOrganism(org);

        // 16 ticks: 3× CALL COUNTER (4 ticks each) + 1× CALL COUNTER_B (3 ticks) + WAIT (1 tick)
        for (int i = 0; i < 16; i++) {
            sim.tick();
        }

        assertThat(org.isInstructionFailed()).as("Failure: " + org.getFailureReason()).isFalse();

        // COUNTER was called 3x, each time incrementing SDR0 and copying to DR0
        Molecule dr0 = Molecule.fromInt((Integer) org.readOperand(0));
        assertThat(dr0.toScalarValue())
                .as("DR0 should be 3 after three COUNTER calls")
                .isEqualTo(3);

        // COUNTER_B has its own SDR0 (never incremented), copied to DR1
        Molecule dr1 = Molecule.fromInt((Integer) org.readOperand(1));
        assertThat(dr1.toScalarValue())
                .as("DR1 should be 0 — COUNTER_B has an independent SDR backing store")
                .isEqualTo(0);
    }

    /**
     * Verifies LREF location parameter passing: a procedure receives a location register
     * by reference, modifies it (clears to [0,0]), and the modified value is written back
     * to the caller's source register after RET.
     */
    @Test
    @Tag("integration")
    void lrefLocationParameterPassingAndWriteBack() throws Exception {
        String source = String.join("\n",
                // Main: save DP to LR0, call CLEAR_POS LREF %LR0, check LR0 is [0,0]
                "DPLR %LR0",                    // LR0 = current DP (non-zero position)
                "CALL CLEAR_POS LREF %LR0",     // Pass LR0 by location reference
                "WAIT",
                // CLEAR_POS clears the passed location to [0,0]
                ".ORG 0|1",
                "EXPORT .PROC CLEAR_POS LREF lPos",
                "  CRLR lPos",                  // Clear FLR0 to [0,0]
                "  RET",
                ".ENDP"
        );

        Compiler compiler = new Compiler();
        EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
        ProgramArtifact artifact = compiler.compile(Arrays.asList(source.split("\\r?\\n")), "lref_test.s", envProps);
        assertThat(artifact).isNotNull();

        Environment env = new Environment(envProps);
        Simulation sim = SimulationTestUtils.createSimulation(env);

        for (Map.Entry<int[], Integer> e : artifact.machineCodeLayout().entrySet()) {
            env.setMolecule(Molecule.fromInt(e.getValue()), e.getKey());
        }

        Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
        org.setProgramId(artifact.programId());
        sim.addOrganism(org);

        // Run enough ticks: DPLR(1) + PUSL(2) + CALL(3) + POPL(4) + CRLR(5) + PUSL(6) + RET(7) + POPL(8) + WAIT(9)
        for (int i = 0; i < 15; i++) {
            sim.tick();
        }

        assertThat(org.isInstructionFailed()).as("Failure: " + org.getFailureReason()).isFalse();

        // Verify LREF write-back: LR0 should now be [0,0] because CLEAR_POS cleared FLR0
        int[] lr0Value = (int[]) org.readOperand(RegisterBank.LR.base);
        assertThat(lr0Value).as("LR0 should be [0,0] after LREF write-back from CLEAR_POS").isEqualTo(new int[]{0, 0});
    }

    /**
     * Tests LVAL with a label argument via procedure call.
     * PSLI resolves the label via fuzzy matching at CALL time,
     * the procedure receives the resolved position in FLR0 via POPL.
     * The procedure copies the FLR value into LR0 for verification after RET.
     */
    @Test
    @Tag("integration")
    void lvalWithLabelPassesResolvedPositionToProcedure() throws Exception {
        String source = String.join("\n",
                ".ORG 0|10",
                "TARGET:",
                "NOP",
                ".ORG 0|0",
                "CALL SAVE_POS LVAL TARGET",
                "WAIT",
                ".ORG 0|3",
                "EXPORT .PROC SAVE_POS LVAL lDest",
                "  LRLR %LR0 lDest",        // Copy FLR0 (resolved label position) into LR0
                "  RET",
                ".ENDP"
        );

        Compiler compiler = new Compiler();
        EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
        ProgramArtifact artifact = compiler.compile(Arrays.asList(source.split("\\r?\\n")), "lval_label_test.s", envProps);
        assertThat(artifact).isNotNull();

        Environment env = new Environment(envProps);
        Simulation sim = SimulationTestUtils.createSimulation(env);

        for (Map.Entry<int[], Integer> e : artifact.machineCodeLayout().entrySet()) {
            env.setMolecule(Molecule.fromInt(e.getValue()), e.getKey());
        }

        Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
        org.setProgramId(artifact.programId());
        sim.addOrganism(org);

        for (int i = 0; i < 20; i++) {
            sim.tick();
        }

        assertThat(org.isInstructionFailed()).as("Failure: " + org.getFailureReason()).isFalse();

        // LR0 should contain TARGET's resolved position [0,10]
        int[] lr0Value = (int[]) org.readOperand(RegisterBank.LR.base);
        assertThat(lr0Value).as("LR0 should contain TARGET's position [0,10] passed via LVAL").isEqualTo(new int[]{0, 10});
    }

    /**
     * Tests the PSLI instruction directly: resolves a label via fuzzy matching
     * and pushes the resolved position onto the location stack.
     */
    @Test
    @Tag("integration")
    void psliPushesResolvedLabelPositionOntoLocationStack() throws Exception {
        String source = String.join("\n",
                ".ORG 0|10",
                "TARGET:",
                "NOP",
                ".ORG 0|0",
                "PSLI TARGET",
                "POPL %LR0",
                "WAIT"
        );

        Compiler compiler = new Compiler();
        EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
        ProgramArtifact artifact = compiler.compile(Arrays.asList(source.split("\\r?\\n")), "psli_test.s", envProps);
        assertThat(artifact).isNotNull();

        Environment env = new Environment(envProps);
        Simulation sim = SimulationTestUtils.createSimulation(env);

        for (Map.Entry<int[], Integer> e : artifact.machineCodeLayout().entrySet()) {
            env.setMolecule(Molecule.fromInt(e.getValue()), e.getKey());
        }

        Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
        org.setProgramId(artifact.programId());
        sim.addOrganism(org);

        for (int i = 0; i < 10; i++) {
            sim.tick();
        }

        assertThat(org.isInstructionFailed()).as("Failure: " + org.getFailureReason()).isFalse();

        int[] lr0Value = (int[]) org.readOperand(RegisterBank.LR.base);
        assertThat(lr0Value).as("LR0 should contain TARGET's position [0,10]").isEqualTo(new int[]{0, 10});
    }

    /**
     * Tests the LRLI instruction directly: resolves a label via fuzzy matching
     * and writes the resolved position into a location register.
     */
    @Test
    @Tag("integration")
    void lrliWritesResolvedLabelPositionToLocationRegister() throws Exception {
        String source = String.join("\n",
                ".ORG 0|10",
                "TARGET:",
                "NOP",
                ".ORG 0|0",
                "LRLI %LR0 TARGET",
                "WAIT"
        );

        Compiler compiler = new Compiler();
        EnvironmentProperties envProps = new EnvironmentProperties(new int[]{64, 64}, true);
        ProgramArtifact artifact = compiler.compile(Arrays.asList(source.split("\\r?\\n")), "lrli_test.s", envProps);
        assertThat(artifact).isNotNull();

        Environment env = new Environment(envProps);
        Simulation sim = SimulationTestUtils.createSimulation(env);

        for (Map.Entry<int[], Integer> e : artifact.machineCodeLayout().entrySet()) {
            env.setMolecule(Molecule.fromInt(e.getValue()), e.getKey());
        }

        Organism org = Organism.create(sim, new int[]{0, 0}, 1000);
        org.setProgramId(artifact.programId());
        sim.addOrganism(org);

        for (int i = 0; i < 10; i++) {
            sim.tick();
        }

        assertThat(org.isInstructionFailed()).as("Failure: " + org.getFailureReason()).isFalse();

        int[] lr0Value = (int[]) org.readOperand(RegisterBank.LR.base);
        assertThat(lr0Value).as("LR0 should contain TARGET's position [0,10]").isEqualTo(new int[]{0, 10});
    }

}
