package org.evochora.datapipeline.api.analytics;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Defines the schema for a Parquet file generated by an analytics plugin.
 * <p>
 * Plugins define their schema declaratively, and the indexer handles
 * DuckDB table creation and Parquet generation.
 * <p>
 * <strong>Example:</strong>
 * <pre>{@code
 * ParquetSchema schema = ParquetSchema.builder()
 *     .column("tick", ColumnType.BIGINT)
 *     .column("alive_count", ColumnType.INTEGER)
 *     .column("avg_energy", ColumnType.DOUBLE)
 *     .column("births", ColumnType.INTEGER, Aggregation.SUM)
 *     .build();
 * }</pre>
 * <p>
 * <strong>Aggregation.</strong> Every column says how it survives a coarser level of detail: a
 * {@link Aggregation#SAMPLE} column, the default, keeps the value of the recording the level's row
 * stands on, a {@link Aggregation#SUM} column the values of every recording of the level's window
 * added up. Rows of a {@code SUM} column are read by adding those falling into a range, never by
 * picking one, since a window reaching the end of a batch leaves its part as a row of its own.
 * <p>
 * <strong>Thread Safety:</strong> Immutable after construction.
 */
public final class ParquetSchema {
    
    private final List<Column> columns;
    
    private ParquetSchema(List<Column> columns) {
        this.columns = Collections.unmodifiableList(new ArrayList<>(columns));
    }
    
    /**
     * Returns the list of columns in this schema.
     *
     * @return Immutable list of columns
     */
    public List<Column> getColumns() {
        return columns;
    }
    
    /**
     * Returns the number of columns in this schema.
     *
     * @return Column count
     */
    public int getColumnCount() {
        return columns.size();
    }
    
    /**
     * Returns the positions of the columns declared {@link Aggregation#SUM}, in column order.
     * <p>
     * An empty result says that every column of this schema is sampled, which is the case that
     * needs no accumulation at all.
     *
     * @return Indexes of the summed columns, empty if the schema has none
     */
    public int[] summedColumnIndexes() {
        int count = 0;
        for (Column column : columns) {
            if (column.aggregation() == Aggregation.SUM) {
                count++;
            }
        }
        int[] indexes = new int[count];
        int next = 0;
        for (int i = 0; i < columns.size(); i++) {
            if (columns.get(i).aggregation() == Aggregation.SUM) {
                indexes[next++] = i;
            }
        }
        return indexes;
    }

    /**
     * Generates the DuckDB CREATE TABLE SQL statement for this schema.
     *
     * @param tableName The table name to use
     * @return SQL CREATE TABLE statement
     */
    public String toCreateTableSql(String tableName) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLE ").append(tableName).append(" (");
        
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) sb.append(", ");
            Column col = columns.get(i);
            sb.append(col.name()).append(" ").append(col.type().getSqlType());
        }
        
        sb.append(")");
        return sb.toString();
    }
    
    /**
     * Generates the DuckDB INSERT statement for this schema.
     *
     * @param tableName The table name to insert into
     * @return SQL INSERT statement with ? placeholders
     */
    public String toInsertSql(String tableName) {
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO ").append(tableName).append(" VALUES (");
        
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append("?");
        }
        
        sb.append(")");
        return sb.toString();
    }
    
    /**
     * Creates a new schema builder.
     *
     * @return New builder instance
     */
    public static Builder builder() {
        return new Builder();
    }
    
    /**
     * Represents a single column in the schema.
     *
     * @param name Column name (must be valid SQL identifier)
     * @param type Column data type
     * @param aggregation How the column carries into a coarser level of detail
     */
    public record Column(String name, ColumnType type, Aggregation aggregation) {
        /**
         * Creates a new column definition.
         *
         * @param name Column name (must not be null or empty)
         * @param type Column type (must not be null)
         * @param aggregation Aggregation (must not be null)
         * @throws IllegalArgumentException if name is null/empty, type or aggregation is null, or
         *         a summed column has a type whose values cannot be added
         */
        public Column {
            if (name == null || name.isBlank()) {
                throw new IllegalArgumentException("Column name must not be null or empty");
            }
            if (type == null) {
                throw new IllegalArgumentException("Column type must not be null");
            }
            if (aggregation == null) {
                throw new IllegalArgumentException("Column aggregation must not be null");
            }
            // Summing a rate or an average produces a number nothing measures, and summing text
            // or a flag produces nothing at all, so only whole numbers may be declared summed
            if (aggregation == Aggregation.SUM && !type.isIntegral()) {
                throw new IllegalArgumentException("Column '" + name + "' is declared "
                    + Aggregation.SUM + " but has type " + type
                    + "; a summed column counts events and must be INTEGER or BIGINT");
            }
        }
    }
    
    /**
     * Builder for constructing ParquetSchema instances.
     */
    public static final class Builder {
        private final List<Column> columns = new ArrayList<>();
        
        private Builder() {}
        
        /**
         * Adds a sampled column to the schema, which keeps the value of the recording a coarser
         * level's row stands on.
         *
         * @param name Column name
         * @param type Column type
         * @return This builder for chaining
         */
        public Builder column(String name, ColumnType type) {
            return column(name, type, Aggregation.SAMPLE);
        }

        /**
         * Adds a column to the schema, saying how it carries into a coarser level of detail.
         *
         * @param name Column name
         * @param type Column type
         * @param aggregation {@link Aggregation#SAMPLE} for a state or a rate,
         *        {@link Aggregation#SUM} for a count of events
         * @return This builder for chaining
         * @throws IllegalArgumentException if a summed column has a type whose values cannot be
         *         added
         */
        public Builder column(String name, ColumnType type, Aggregation aggregation) {
            columns.add(new Column(name, type, aggregation));
            return this;
        }
        
        /**
         * Builds the schema.
         *
         * @return Immutable ParquetSchema
         * @throws IllegalStateException if no columns were added
         */
        public ParquetSchema build() {
            if (columns.isEmpty()) {
                throw new IllegalStateException("Schema must have at least one column");
            }
            return new ParquetSchema(columns);
        }
    }
}

