package org.evochora.datapipeline.api.analytics;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Defines the schema for a Parquet file generated by an analytics plugin.
 * <p>
 * Plugins define their schema declaratively, and the indexer handles
 * DuckDB table creation and Parquet generation.
 * <p>
 * <strong>Example:</strong>
 * <pre>{@code
 * ParquetSchema schema = ParquetSchema.builder()
 *     .column("tick", ColumnType.BIGINT)
 *     .column("alive_count", ColumnType.INTEGER)
 *     .column("avg_energy", ColumnType.DOUBLE)
 *     .build();
 * }</pre>
 *
 * <strong>Thread Safety:</strong> Immutable after construction.
 */
public final class ParquetSchema {
    
    private final List<Column> columns;
    
    private ParquetSchema(List<Column> columns) {
        this.columns = Collections.unmodifiableList(new ArrayList<>(columns));
    }
    
    /**
     * Returns the list of columns in this schema.
     *
     * @return Immutable list of columns
     */
    public List<Column> getColumns() {
        return columns;
    }
    
    /**
     * Returns the number of columns in this schema.
     *
     * @return Column count
     */
    public int getColumnCount() {
        return columns.size();
    }
    
    /**
     * Generates the DuckDB CREATE TABLE SQL statement for this schema.
     *
     * @param tableName The table name to use
     * @return SQL CREATE TABLE statement
     */
    public String toCreateTableSql(String tableName) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE TABLE ").append(tableName).append(" (");
        
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) sb.append(", ");
            Column col = columns.get(i);
            sb.append(col.name()).append(" ").append(col.type().getSqlType());
        }
        
        sb.append(")");
        return sb.toString();
    }
    
    /**
     * Generates the DuckDB INSERT statement for this schema.
     *
     * @param tableName The table name to insert into
     * @return SQL INSERT statement with ? placeholders
     */
    public String toInsertSql(String tableName) {
        StringBuilder sb = new StringBuilder();
        sb.append("INSERT INTO ").append(tableName).append(" VALUES (");
        
        for (int i = 0; i < columns.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append("?");
        }
        
        sb.append(")");
        return sb.toString();
    }
    
    /**
     * Creates a new schema builder.
     *
     * @return New builder instance
     */
    public static Builder builder() {
        return new Builder();
    }
    
    /**
     * Represents a single column in the schema.
     *
     * @param name Column name (must be valid SQL identifier)
     * @param type Column data type
     */
    public record Column(String name, ColumnType type) {
        /**
         * Creates a new column definition.
         *
         * @param name Column name (must not be null or empty)
         * @param type Column type (must not be null)
         * @throws IllegalArgumentException if name is null/empty or type is null
         */
        public Column {
            if (name == null || name.isBlank()) {
                throw new IllegalArgumentException("Column name must not be null or empty");
            }
            if (type == null) {
                throw new IllegalArgumentException("Column type must not be null");
            }
        }
    }
    
    /**
     * Builder for constructing ParquetSchema instances.
     */
    public static final class Builder {
        private final List<Column> columns = new ArrayList<>();
        
        private Builder() {}
        
        /**
         * Adds a column to the schema.
         *
         * @param name Column name
         * @param type Column type
         * @return This builder for chaining
         */
        public Builder column(String name, ColumnType type) {
            columns.add(new Column(name, type));
            return this;
        }
        
        /**
         * Builds the schema.
         *
         * @return Immutable ParquetSchema
         * @throws IllegalStateException if no columns were added
         */
        public ParquetSchema build() {
            if (columns.isEmpty()) {
                throw new IllegalStateException("Schema must have at least one column");
            }
            return new ParquetSchema(columns);
        }
    }
}

