# ===============================================================
# ==         Override Configuration for DEMO Environment       ==
# ===============================================================
#
# This file includes the standard configuration and overrides
# specific values for the production demo system.

# 1. Include the standard configuration file as a base.
#    Both files are in the same directory inside the container.
include "evochora.conf"

# 2. Override specific settings for the demo environment.
# --- Demo-specific Overrides ---

pipeline {
  autoStart = false

  database {
      # 1 GB Cache (1048576 KB) for the demo database.
      jdbcUrl = "jdbc:h2:/home/appuser/app/data/database/indexdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=30000;WRITE_DELAY=100;MAX_MEMORY_ROWS=100000;CACHE_SIZE=1048576"
  }

  services {
    simulation-engine {
      options {
        pauseTicks = [200000, 300000, 400000, 500000]
      }
    }
  }
}

node {
  processes {
    h2-console.options.network.host = "0.0.0.0"
    h2-tcp-server.options.tcpAllowOthers = true
  }
}
