/*
 * SPDX-FileCopyrightText: 2024-2024 EvoChora contributors
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package org.evochora.compiler.model.ir;

import org.evochora.compiler.api.SourceInfo;

import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Represents a generic instruction in the intermediate representation.
 * Non-final to allow feature-specific subtypes (e.g., IrCallInstruction).
 */
public class IrInstruction implements IrItem {
    private final String opcode;
    private final List<IrOperand> operands;
    private final SourceInfo source;
    private final boolean synthetic;

    /**
     * Constructor for instructions with standard operands.
     *
     * @param opcode   The instruction opcode.
     * @param operands The list of operands.
     * @param source The source information.
     */
    public IrInstruction(final String opcode, final List<IrOperand> operands, final SourceInfo source) {
        this(opcode, operands, source, false);
    }

    /**
     * Full constructor with all fields including synthetic flag.
     *
     * @param opcode    The instruction opcode.
     * @param operands  The main operands.
     * @param source    The source information.
     * @param synthetic Whether this instruction was generated by the compiler.
     */
    public IrInstruction(
            final String opcode,
            final List<IrOperand> operands,
            final SourceInfo source,
            final boolean synthetic) {
        this.opcode = opcode;
        this.operands = Collections.unmodifiableList(operands);
        this.source = source;
        this.synthetic = synthetic;
    }

    /**
     * Factory method to create a synthetic (compiler-generated) instruction.
     *
     * @param opcode   The instruction opcode.
     * @param operands The list of operands.
     * @param source   The source information.
     * @return A new IrInstruction marked as synthetic.
     */
    public static IrInstruction synthetic(final String opcode, final List<IrOperand> operands, final SourceInfo source) {
        return new IrInstruction(opcode, operands, source, true);
    }

    public String opcode() {
        return opcode;
    }

    public List<IrOperand> operands() {
        return operands;
    }

    @Override
    public SourceInfo source() {
        return source;
    }

    /**
     * Returns whether this instruction is synthetic (compiler-generated).
     */
    public boolean synthetic() {
        return synthetic;
    }

    @Override
    public String toString() {
        return "IrInstruction{" +
                "opcode='" + opcode + '\'' +
                ", operands=" + operands +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        IrInstruction that = (IrInstruction) o;
        return Objects.equals(opcode, that.opcode) &&
                Objects.equals(operands, that.operands);
    }

    @Override
    public int hashCode() {
        return Objects.hash(opcode, operands);
    }
}
