package org.evochora.compiler.features.ctx;

import org.evochora.compiler.frontend.module.PlacementContext;
import org.evochora.compiler.frontend.parser.IParserStatementHandler;
import org.evochora.compiler.frontend.parser.IParsingContext;
import org.evochora.compiler.model.ast.AstNode;

/**
 * Parser handler for the {@code .PUSH_CTX} directive (Phase 3). Extracts the
 * placement context (source path and alias chain) carried by the token and
 * produces a {@link PushCtxNode}.
 */
public class PushCtxDirectiveHandler implements IParserStatementHandler {
    @Override
    public AstNode parse(IParsingContext context) {
        Object value = context.peek().value();
        context.advance(); // consume .PUSH_CTX

        if (!(value instanceof PlacementContext pc)) {
            // The directive is generated by the compiler, never written in source, and both places
            // that emit it attach a PlacementContext. Anything else means the token was built
            // wrongly, which is worth saying rather than turning into a context without a path.
            throw new IllegalStateException(".PUSH_CTX carries no placement context but "
                    + (value == null ? "null" : value.getClass().getName()));
        }
        return new PushCtxNode(pc.sourcePath(), pc.aliasChain());
    }
}
