package org.evochora.compiler.backend.emit;

import org.evochora.compiler.api.CompilationException;
import org.evochora.compiler.api.Expansion;
import org.evochora.compiler.api.MachineInstructionInfo;
import org.evochora.compiler.api.SourceFile;
import org.evochora.compiler.api.SourceInfo;
import org.evochora.compiler.backend.layout.LayoutResult;
import org.evochora.compiler.isa.IInstructionSet;
import org.evochora.compiler.model.ir.IrImm;
import org.evochora.compiler.model.ir.IrInstruction;
import org.evochora.compiler.model.ir.IrLabelRef;
import org.evochora.compiler.model.ir.IrOperand;
import org.evochora.compiler.model.ir.IrReg;
import org.evochora.compiler.model.ir.IrTypedImm;
import org.evochora.compiler.model.ir.IrVec;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Collects, for every source line, the machine instructions the compiler generated for it,
 * as the visualizer shows them next to the source: the opcode, the operands as text, and
 * whether the instruction was written by the programmer or generated by the compiler.
 * <p>
 * An instruction stands under the placement, file and expansion of its position: the instance of
 * an entry of the program's sources, one inclusion of a file, or the number of an instance of
 * injected tokens that is no inclusion, whose template stands on the lines of an entry. A
 * position must lead to an entry, directly or through the definitions of the expansions it stands
 * in; one that does not is a defect of the compiler and is reported as such.
 * <p>
 * A label reference is shown as the delta from the opcode's cell to the label's cell, the
 * way the instruction will jump; every other operand is shown as written.
 */
final class SourceLineIndex {

    private final LayoutResult layout;
    private final IInstructionSet isa;
    private final Map<Integer, Expansion> expansions;
    private final Set<EntryKey> entries = new HashSet<>();
    private final Map<String, Map<String, Map<Integer, Map<Integer, List<MachineInstructionInfo>>>>> instructionsByLine =
            new HashMap<>();

    /**
     * Creates an empty index over a layout.
     *
     * @param layout         The layout, for the addresses and coordinates of labels.
     * @param isa            The instruction set, for the text a typed value is shown as.
     * @param sources        The entries of the program's sources, which every recorded position
     *                       must name.
     * @param expansions     Every instance of injected tokens that is no inclusion, by its number,
     *                       with the position of its template.
     */
    SourceLineIndex(LayoutResult layout, IInstructionSet isa, List<SourceFile> sources,
                    Map<Integer, Expansion> expansions) {
        this.layout = layout;
        this.isa = isa;
        this.expansions = expansions;
        for (SourceFile source : sources) {
            entries.add(new EntryKey(source.placement(), source.resolvedPath(), source.instance()));
        }
    }

    /** An entry of the sources by its placement, resolved path and instance. */
    private record EntryKey(String placement, String fileName, int instance) {
    }

    /**
     * Records an instruction under the source line it came from, in the expansion of its
     * position. An instruction without a source location is not recorded.
     *
     * @param instruction  The instruction as it was emitted.
     * @param opcodeAddress The linear address of the instruction's opcode cell.
     * @param opcodeCoord   The coordinate of that cell.
     * @throws CompilationException if the position of the instruction leads to no entry of the
     *         sources, which means the preprocessor and the source map disagree.
     */
    void note(IrInstruction instruction, int opcodeAddress, int[] opcodeCoord) throws CompilationException {
        SourceInfo src = instruction.source();
        if (src == null) {
            return;
        }
        String operands = instruction.operands().stream()
                .map(op -> format(op, opcodeCoord))
                .collect(Collectors.joining(" "));
        String fileName = src.fileName() != null ? src.fileName() : "<unknown>";
        if (!leadsToAnEntry(src.placement(), fileName, src.expansion())) {
            throw new CompilationException(SourceInfo.locate(src, "Internal error: the position of '" + instruction.opcode()
                    + "' names no source entry (placement '" + src.placement() + "', expansion " + src.expansion() + ")"));
        }
        instructionsByLine.computeIfAbsent(src.placement(), k -> new HashMap<>())
                .computeIfAbsent(fileName, k -> new HashMap<>())
                .computeIfAbsent(src.expansion(), k -> new HashMap<>())
                .computeIfAbsent(src.lineNumber(), k -> new ArrayList<>())
                .add(new MachineInstructionInfo(opcodeAddress, instruction.opcode(), operands, instruction.synthetic()));
    }

    /**
     * Reports whether a position names an entry, or stands in an expansion whose template, followed
     * through the definitions of enclosing expansions, stands in one. The template of an expansion
     * was read before the expansion was made, so its number is smaller and the walk ends.
     */
    private boolean leadsToAnEntry(String placement, String fileName, int expansion) {
        String atPlacement = placement;
        String atFile = fileName;
        int at = expansion;
        while (!entries.contains(new EntryKey(atPlacement, atFile, at))) {
            Expansion enclosing = expansions.get(at);
            if (enclosing == null || enclosing.definedAt().expansion() >= at) {
                return false;
            }
            atPlacement = enclosing.definedAt().placement();
            atFile = enclosing.definedAt().fileName();
            at = enclosing.definedAt().expansion();
        }
        return true;
    }

    /**
     * Returns the collected instructions by placement, file name, expansion and line, ordered by
     * address within a line. Two inclusions of one file, and the expansions of one template, share
     * its lines, so the expansion comes first.
     *
     * @return A new map; the index is not modified.
     */
    Map<String, Map<String, Map<Integer, Map<Integer, List<MachineInstructionInfo>>>>> byLine() {
        Map<String, Map<String, Map<Integer, Map<Integer, List<MachineInstructionInfo>>>>> sorted = new HashMap<>();
        instructionsByLine.forEach((placement, files) -> files.forEach((fileName, byExpansion) -> byExpansion.forEach(
                (expansion, lines) -> lines.forEach((line, instructions) -> sorted
                        .computeIfAbsent(placement, k -> new HashMap<>())
                        .computeIfAbsent(fileName, k -> new HashMap<>())
                        .computeIfAbsent(expansion, k -> new HashMap<>())
                        .put(line, instructions.stream()
                                .sorted((a, b) -> Integer.compare(a.linearAddress(), b.linearAddress()))
                                .toList())))));
        return sorted;
    }

    private String format(IrOperand op, int[] opcodeCoord) {
        return switch (op) {
            case IrReg r -> r.name();
            case IrImm imm -> String.valueOf(imm.value());
            case IrTypedImm ti -> ti.typeName() + ":" + formatTypedValue(ti);
            case IrVec vec -> join(vec.components());
            case IrLabelRef ref -> formatLabelDelta(ref, opcodeCoord);
        };
    }

    /**
     * Formats the value of a typed immediate the way the target shows a value of that type. A
     * type name the target does not know is rejected where the operand is encoded; here its value
     * is shown as written.
     */
    private String formatTypedValue(IrTypedImm operand) {
        return isa.moleculeType(operand.typeName())
                .map(type -> isa.formatValue(type, (int) operand.value()))
                .orElseGet(() -> String.valueOf(operand.value()));
    }

    /**
     * Formats a label reference as the delta from the opcode to the label, or as the label
     * name if the layout does not know the label.
     */
    private String formatLabelDelta(IrLabelRef ref, int[] opcodeCoord) {
        Integer targetAddr = layout.labelToAddress().get(ref.labelName());
        if (targetAddr != null) {
            int[] targetCoord = layout.linearAddressToCoord().get(targetAddr);
            if (targetCoord != null && opcodeCoord != null) {
                int dims = Math.max(opcodeCoord.length, targetCoord.length);
                int[] delta = new int[dims];
                for (int d = 0; d < dims; d++) {
                    int s = d < opcodeCoord.length ? opcodeCoord[d] : 0;
                    int t = d < targetCoord.length ? targetCoord[d] : 0;
                    delta[d] = t - s;
                }
                return join(delta);
            }
        }
        return ref.labelName();
    }

    private static String join(int[] components) {
        return Arrays.stream(components).mapToObj(String::valueOf).collect(Collectors.joining("|"));
    }
}
