package org.evochora.compiler.backend.emit;

import org.evochora.compiler.api.MachineInstructionInfo;
import org.evochora.compiler.api.SourceInfo;
import org.evochora.compiler.backend.layout.LayoutResult;
import org.evochora.compiler.model.ir.IrImm;
import org.evochora.compiler.model.ir.IrInstruction;
import org.evochora.compiler.model.ir.IrLabelRef;
import org.evochora.compiler.model.ir.IrOperand;
import org.evochora.compiler.model.ir.IrReg;
import org.evochora.compiler.model.ir.IrTypedImm;
import org.evochora.compiler.model.ir.IrVec;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Collects, for every source line, the machine instructions the compiler generated for it,
 * as the visualizer shows them next to the source: the opcode, the operands as text, and
 * whether the instruction was written by the programmer or generated by the compiler.
 * <p>
 * A label reference is shown as the delta from the opcode's cell to the label's cell, the
 * way the instruction will jump; every other operand is shown as written.
 */
final class SourceLineIndex {

    private final LayoutResult layout;
    private final Map<String, List<MachineInstructionInfo>> instructionsByLine = new HashMap<>();

    /**
     * Creates an empty index over a layout.
     *
     * @param layout The layout, for the addresses and coordinates of labels.
     */
    SourceLineIndex(LayoutResult layout) {
        this.layout = layout;
    }

    /**
     * Records an instruction under the source line it came from. An instruction without a
     * source location is not recorded.
     *
     * @param instruction  The instruction as it was emitted.
     * @param opcodeAddress The linear address of the instruction's opcode cell.
     * @param opcodeCoord   The coordinate of that cell.
     */
    void note(IrInstruction instruction, int opcodeAddress, int[] opcodeCoord) {
        SourceInfo src = instruction.source();
        if (src == null) {
            return;
        }
        String operands = instruction.operands().stream()
                .map(op -> format(op, opcodeCoord))
                .collect(Collectors.joining(" "));
        instructionsByLine.computeIfAbsent(lineKey(src), k -> new ArrayList<>())
                .add(new MachineInstructionInfo(opcodeAddress, instruction.opcode(), operands, instruction.synthetic()));
    }

    /**
     * Returns the collected instructions, keyed by "fileName:lineNumber" and ordered by
     * address within a line.
     *
     * @return A new map; the index is not modified.
     */
    Map<String, List<MachineInstructionInfo>> byLine() {
        Map<String, List<MachineInstructionInfo>> sorted = new LinkedHashMap<>();
        for (Map.Entry<String, List<MachineInstructionInfo>> entry : instructionsByLine.entrySet()) {
            sorted.put(entry.getKey(), entry.getValue().stream()
                    .sorted((a, b) -> Integer.compare(a.linearAddress(), b.linearAddress()))
                    .toList());
        }
        return sorted;
    }

    private static String lineKey(SourceInfo src) {
        String fileName = src.fileName() != null ? src.fileName() : "<unknown>";
        return fileName + ":" + src.lineNumber();
    }

    private String format(IrOperand op, int[] opcodeCoord) {
        return switch (op) {
            case IrReg r -> r.name();
            case IrImm imm -> String.valueOf(imm.value());
            case IrTypedImm ti -> ti.typeName() + ":" + ti.value();
            case IrVec vec -> join(vec.components());
            case IrLabelRef ref -> formatLabelDelta(ref, opcodeCoord);
        };
    }

    /**
     * Formats a label reference as the delta from the opcode to the label, or as the label
     * name if the layout does not know the label.
     */
    private String formatLabelDelta(IrLabelRef ref, int[] opcodeCoord) {
        Integer targetAddr = layout.labelToAddress().get(ref.labelName());
        if (targetAddr != null) {
            int[] targetCoord = layout.linearAddressToCoord().get(targetAddr);
            if (targetCoord != null && opcodeCoord != null) {
                int dims = Math.max(opcodeCoord.length, targetCoord.length);
                int[] delta = new int[dims];
                for (int d = 0; d < dims; d++) {
                    int s = d < opcodeCoord.length ? opcodeCoord[d] : 0;
                    int t = d < targetCoord.length ? targetCoord[d] : 0;
                    delta[d] = t - s;
                }
                return join(delta);
            }
        }
        return ref.labelName();
    }

    private static String join(int[] components) {
        return Arrays.stream(components).mapToObj(String::valueOf).collect(Collectors.joining("|"));
    }
}
